name: CI

on:
  push:
    paths-ignore:
      - "build/**"
      - "public/**"
  pull_request:
    paths-ignore:
      - "build/**"
      - "public/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
      - name: Install dependencies
        uses: jaid/action-npm-install@v1.2.1
      - name: Build and test
        run: npm test
