name: CI

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v1
      - name: Install PNPM
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install-test --frozen-lockfile=false
